[package]
name = "instistats"
version = "0.1.0"
authors = ["Ben Morrison <ben@gbmor.dev>"]
edition = "2018"

[dependencies]
serde_json = "^1.0.40"

[dependencies.serde]
version = "^1.0"
features = ["derive"]
